# SPDX-License-Identifier: GPL-2.0-or-later
<#
.SYNOPSIS
  Build Wireshark (pinned 4.7 revision) with the AI Inspector plugins on Windows,
  run the tests, and optionally create an installer that includes the plugins.

.DESCRIPTION
  Windows counterpart of tools/build-development.sh. Run it from a
  "x64 Native Tools Command Prompt / Developer PowerShell for VS" window.

  Prerequisites (see docs/development-setup.md, "Windows"):
    Visual Studio 2022 or 2026 with "Desktop development with C++"
    Qt 6 (MSVC 64-bit), Python 3, Git, CMake, winflexbison3, Strawberry Perl
    NSIS (only for -Installer)

.EXAMPLE
  .\tools\build-windows.ps1 -QtDir C:\Qt\6.10.3\msvc2022_64
  .\tools\build-windows.ps1 -QtDir C:\Qt\6.10.3\msvc2022_64 -Installer
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)] [string] $QtDir,          # Qt install, e.g. C:\Qt\6.10.3\msvc2022_64
    [string] $BuildDir = "",                                 # default: <repo>\build-windows
    [string] $ThirdPartyDir = "",                            # default: <repo>\..\wireshark-third-party
    [string] $Configuration = "RelWithDebInfo",
    [string] $Generator = "",                                # default: newest Visual Studio found by CMake
    [switch] $SkipTests,
    [switch] $Installer                                      # build the NSIS installer with the plugins included
)

$ErrorActionPreference = "Stop"
function Say($msg) { Write-Host "`n==> $msg" -ForegroundColor Cyan }
function Need($cmd, $hint) {
    if (-not (Get-Command $cmd -ErrorAction SilentlyContinue)) { throw "Missing required tool: $cmd ($hint)" }
}
function Run($exe, [string[]] $argv) {
    & $exe @argv
    if ($LASTEXITCODE -ne 0) { throw "$exe failed with exit code $LASTEXITCODE" }
}

$Root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$Upstream = Join-Path $Root "upstream\wireshark"
if (-not $BuildDir) { $BuildDir = Join-Path $Root "build-windows" }
if (-not $ThirdPartyDir) { $ThirdPartyDir = Join-Path (Split-Path $Root -Parent) "wireshark-third-party" }

Need cmake "Visual Studio 'C++ CMake tools' or https://cmake.org"
Need git "https://git-scm.com/download/win"
Need python "https://python.org"
Need cl "run this script from a Visual Studio Developer PowerShell (x64)"
if (-not (Test-Path (Join-Path $QtDir "lib\cmake\Qt6"))) { throw "Qt 6 not found in $QtDir (expected lib\cmake\Qt6)" }

# --- Wireshark source at the pinned commit -------------------------------------------
$versionCmake = Get-Content (Join-Path $Root "cmake\AIInspectorVersion.cmake") -Raw
$commit = [regex]::Match($versionCmake, 'AI_INSPECTOR_WIRESHARK_COMMIT\s+"([0-9a-f]+)"').Groups[1].Value
if (-not (Test-Path (Join-Path $Upstream "CMakeLists.txt"))) {
    Say "Fetching Wireshark $commit"
    New-Item -ItemType Directory -Force -Path $Upstream | Out-Null
    Run git @("-C", $Upstream, "init", "-q")
    Run git @("-C", $Upstream, "remote", "add", "origin", "https://gitlab.com/wireshark/wireshark.git")
    Run git @("-C", $Upstream, "fetch", "--depth", "1", "origin", $commit)
    Run git @("-C", $Upstream, "checkout", "-q", "FETCH_HEAD")
}

# --- Register the plugins in the Wireshark tree --------------------------------------
# Same stubs as build-development.sh; they include our real CMakeLists.
Say "Registering AI Inspector plugin directories in the source tree"
$stubs = @{
    "plugins\epan\ai_inspector_engine" = 'include("${AI_INSPECTOR_SOURCE_DIR}/native/engine/CMakeLists.txt")'
    "plugins\ui\ai_inspector"          = 'include("${AI_INSPECTOR_SOURCE_DIR}/native/ui/CMakeLists.txt")'
}
foreach ($dir in $stubs.Keys) {
    $full = Join-Path $Upstream $dir
    New-Item -ItemType Directory -Force -Path $full | Out-Null
    Set-Content -Encoding ascii -Path (Join-Path $full "CMakeLists.txt") -Value "# Generated by AI Inspector tools/build-windows.ps1`n$($stubs[$dir])"
}

# The NSIS installer script includes packaging\nsis\custom_plugins.txt inside its
# epan plugin section; add the engine there and the UI plugin to a "ui" folder.
$customPlugins = @'
File "${STAGING_DIR}\plugins\wireshark\${MAJOR_VERSION}.${MINOR_VERSION}\epan\ai_inspector_engine.dll"
SetOutPath '$INSTDIR\plugins\${MAJOR_VERSION}.${MINOR_VERSION}\ui'
File "${STAGING_DIR}\plugins\wireshark\${MAJOR_VERSION}.${MINOR_VERSION}\ui\ai_inspector.dll"
'@
Set-Content -Encoding ascii -Path (Join-Path $Upstream "packaging\nsis\custom_plugins.txt") -Value $customPlugins
# Keep the generated files out of the Wireshark checkout's git status.
$exclude = Join-Path $Upstream ".git\info\exclude"
if (Test-Path $exclude) {
    foreach ($line in @("plugins/epan/ai_inspector_engine/", "plugins/ui/ai_inspector/", "packaging/nsis/custom_plugins.txt")) {
        if (-not (Select-String -Path $exclude -SimpleMatch $line -Quiet)) { Add-Content $exclude $line }
    }
}

# --- Configure and build ---------------------------------------------------------------
Say "Configuring ($BuildDir)"
$env:WIRESHARK_BASE_DIR = $ThirdPartyDir           # Wireshark downloads its Windows libraries here
$cmakeArgs = @("-S", $Upstream, "-B", $BuildDir, "-A", "x64",
    "-DCMAKE_PREFIX_PATH=$QtDir",
    "-DBUILD_stratoshark=OFF",
    "-DCUSTOM_PLUGIN_SRC_DIR=epan/ai_inspector_engine;ui/ai_inspector",
    "-DAI_INSPECTOR_SOURCE_DIR=$($Root -replace '\\','/')")
if ($Generator) { $cmakeArgs = @("-G", $Generator) + $cmakeArgs }
Run cmake $cmakeArgs

Say "Building Wireshark, TShark and the plugins ($Configuration)"
Run cmake @("--build", $BuildDir, "--config", $Configuration, "--parallel",
    "--target", "wireshark", "tshark", "dumpcap", "ai_inspector_engine", "ai_inspector")

$runDir = Join-Path $BuildDir "run\$Configuration"
$engine = Get-ChildItem -Recurse -Path $runDir -Filter "ai_inspector_engine.dll" | Select-Object -First 1
$ui = Get-ChildItem -Recurse -Path $runDir -Filter "ai_inspector.dll" | Select-Object -First 1
if (-not $engine -or -not $ui) { throw "Built plugins not found under $runDir" }

# --- Tests -----------------------------------------------------------------------------
if (-not $SkipTests) {
    Say "Unit tests"
    $testDir = Join-Path $BuildDir "ai-inspector-tests"
    Run cmake @("-S", $Root, "-B", $testDir, "-A", "x64", "-DCMAKE_PREFIX_PATH=$QtDir")
    Run cmake @("--build", $testDir, "--config", $Configuration, "--parallel")
    $env:PATH = "$(Join-Path $QtDir 'bin');$env:PATH"   # Qt DLLs for the test executables
    Run ctest @("--test-dir", $testDir, "-C", $Configuration, "--output-on-failure")

    Say "Integration tests (TShark engine)"
    $venv = Join-Path $BuildDir "ai-inspector-venv"
    if (-not (Test-Path (Join-Path $venv "Scripts\python.exe"))) {
        Run python @("-m", "venv", $venv)
        Run (Join-Path $venv "Scripts\python.exe") @("-m", "pip", "install", "--quiet", "scapy", "cryptography")
    }
    # The in-application GUI self-test is macOS/Linux only for now (it reads Wireshark's stderr).
    Run (Join-Path $venv "Scripts\python.exe") @((Join-Path $Root "tests\run_tests.py"), "--build-dir", $BuildDir)
}

# --- Installer -------------------------------------------------------------------------
if ($Installer) {
    Need makensis "https://nsis.sourceforge.io (add its folder to PATH)"
    # The installer packages everything Wireshark ships (help, translations, extcap
    # tools), so build the default target first; the targets above are only a subset.
    Say "Building the remaining Wireshark targets for packaging"
    Run cmake @("--build", $BuildDir, "--config", $Configuration, "--parallel")
    # The NSIS script packages folders with File /r and aborts when one is empty.
    # Optional pieces (Qt catalogs, the HTML user guide) are missing unless the Qt
    # install ships them / asciidoctor is available, so build what we can and make
    # sure every folder the installer expects has at least one file in it.
    function Ensure-NonEmptyDir([string] $path, [string] $note) {
        New-Item -ItemType Directory -Force -Path $path | Out-Null
        if (Get-ChildItem -Path $path -Recurse -File -ErrorAction SilentlyContinue) { return }
        Write-Warning "$path is empty; packaging a placeholder ($note)"
        Set-Content -Encoding ascii -Path (Join-Path $path "README.txt") -Value $note
    }

    Say "Staging optional installer content"
    # Qt's own translation catalogs, normally deployed by windeployqt.
    $transDir = Join-Path $runDir "translations"
    New-Item -ItemType Directory -Force -Path $transDir | Out-Null
    if (-not (Get-ChildItem -Path $transDir -File -ErrorAction SilentlyContinue)) {
        $qtTrans = Join-Path $QtDir "translations"
        if (Test-Path $qtTrans) {
            Copy-Item (Join-Path $qtTrans "qtbase_*.qm") $transDir -ErrorAction SilentlyContinue
            Copy-Item (Join-Path $qtTrans "qt_*.qm") $transDir -ErrorAction SilentlyContinue
        }
    }
    Ensure-NonEmptyDir $transDir "Qt translation catalogs were not available when this package was built."

    # The HTML user guide needs asciidoctor; build it when that is installed.
    if (Get-Command asciidoctor -ErrorAction SilentlyContinue) {
        & cmake --build $BuildDir --config $Configuration --target user_guide_html
    }
    Ensure-NonEmptyDir (Join-Path $BuildDir "doc\wsug_html_chunked") "The HTML user guide was not built (asciidoctor was not installed). See https://www.wireshark.org/docs/"
    Ensure-NonEmptyDir (Join-Path $BuildDir "doc\wsug_html") "The HTML user guide was not built (asciidoctor was not installed). See https://www.wireshark.org/docs/"

    Say "Building the NSIS installer"
    Run cmake @("--build", $BuildDir, "--config", $Configuration, "--target", "wireshark_nsis_prep")
    Run cmake @("--build", $BuildDir, "--config", $Configuration, "--target", "wireshark_nsis")
    Get-ChildItem -Path (Join-Path $BuildDir "packaging\nsis") -Filter "Wireshark-*.exe" | ForEach-Object { Write-Host "Installer: $($_.FullName)" }
}

Say "Done"
Write-Host "Engine plugin : $($engine.FullName)"
Write-Host "UI plugin     : $($ui.FullName)"
Write-Host "Run Wireshark : $(Join-Path $runDir 'Wireshark.exe')"
Write-Host "In Wireshark  : Tools > AI Inspector > Open Inspector Panel"
