#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-or-later
#
# Build the Wireshark development host together with the AI Inspector
# native plugins (analysis engine + Qt UI), run the tests, and install.
#
#   sh tools/build-development.sh [options]
#
#   --build-dir DIR      build directory (default: build-development)
#   --jobs N             parallel build jobs (default: CPU count)
#   --install MODE       build    : keep plugins in the dev build's own plugin folder (default;
#                                   only this dev build loads them)
#                        personal : move them to ~/.local/lib/wireshark/plugins/<X-Y>/{epan,ui}
#                                   (loaded by every Wireshark X.Y on this account)
#   --skip-tests         do not run the test suites
#   --gui-test           also run the in-application UI self-test (opens Wireshark briefly)
#
# Plugins must be built with the same Wireshark source revision, compiler and
# Qt as the Wireshark that loads them. Do not copy them into another Wireshark.
set -eu

say() { printf '\n==> %s\n' "$*"; }
need() { command -v "$1" >/dev/null 2>&1 || { echo "Missing required tool: $1 ($2)" >&2; exit 1; }; }

ai_inspector_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
upstream="$ai_inspector_root/upstream/wireshark"
build_dir="$ai_inspector_root/build-development"
install_mode=build
run_tests=1
gui_test=0
jobs=$( (sysctl -n hw.ncpu 2>/dev/null || nproc 2>/dev/null || echo 4) | head -1)

while [ $# -gt 0 ]; do
  case "$1" in
    --build-dir) build_dir=$2; shift 2 ;;
    --jobs) jobs=$2; shift 2 ;;
    --install) install_mode=$2; shift 2 ;;
    --skip-tests) run_tests=0; shift ;;
    --gui-test) gui_test=1; shift ;;
    -h|--help) sed -n '3,22p' "$0"; exit 0 ;;
    *) echo "Unknown option: $1" >&2; exit 2 ;;
  esac
done
case "$install_mode" in build|personal) ;; *) echo "--install must be build or personal" >&2; exit 2 ;; esac


need cmake "brew install cmake"
need ninja "brew install ninja"
need python3 "Xcode command line tools or brew install python"
if [ ! -f "$upstream/CMakeLists.txt" ]; then
  say "Wireshark source not found; fetching the pinned revision"
  sh "$ai_inspector_root/tools/fetch-wireshark.sh"
fi

if [ -z "${AI_INSPECTOR_DEPENDENCY_PREFIX:-}" ] && command -v brew >/dev/null 2>&1; then
  AI_INSPECTOR_DEPENDENCY_PREFIX=$(brew --prefix)
fi
prefix_path=${AI_INSPECTOR_DEPENDENCY_PREFIX:-/opt/homebrew}
if command -v brew >/dev/null 2>&1 && brew --prefix qt >/dev/null 2>&1; then
  prefix_path="$(brew --prefix qt);$prefix_path"
fi

say "Registering AI Inspector plugin directories in the source tree"
mkdir -p "$upstream/plugins/epan/ai_inspector_engine" "$upstream/plugins/ui/ai_inspector"
printf '# Generated by AI Inspector tools/build-development.sh\ninclude("${AI_INSPECTOR_SOURCE_DIR}/native/engine/CMakeLists.txt")\n' \
  > "$upstream/plugins/epan/ai_inspector_engine/CMakeLists.txt"
printf '# Generated by AI Inspector tools/build-development.sh\ninclude("${AI_INSPECTOR_SOURCE_DIR}/native/ui/CMakeLists.txt")\n' \
  > "$upstream/plugins/ui/ai_inspector/CMakeLists.txt"

say "Configuring ($build_dir)"
cmake -S "$upstream" -B "$build_dir" -G Ninja \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DCMAKE_PREFIX_PATH="$prefix_path" \
  -DENABLE_APPLICATION_BUNDLE=OFF \
  -DBUILD_stratoshark=OFF \
  -DBUILD_mmdbresolve=OFF \
  -DENABLE_LUA=OFF -DENABLE_SMI=OFF -DENABLE_GNUTLS=OFF \
  -DENABLE_KERBEROS=OFF -DENABLE_SBC=OFF -DENABLE_SPANDSP=OFF \
  -DENABLE_BCG729=OFF -DENABLE_AMRNB=OFF -DENABLE_ILBC=OFF \
  -DENABLE_OPUS=OFF -DENABLE_BROTLI=OFF -DENABLE_MINIZIP=OFF \
  -DCUSTOM_PLUGIN_SRC_DIR="epan/ai_inspector_engine;ui/ai_inspector" \
  -DAI_INSPECTOR_SOURCE_DIR="$ai_inspector_root"

say "Building Wireshark, TShark and the plugins (jobs: $jobs)"
cmake --build "$build_dir" --target wireshark tshark dumpcap ai_inspector_engine ai_inspector -j "$jobs"

# Remove binaries from before the rename to AI Inspector (they would load side by side).
find "$build_dir/run" \( -name 'wireshark_assist.so' -o -name 'wireshark_assist_engine.so' \) -exec rm -f {} + 2>/dev/null || true

engine_so=$(find "$build_dir/run" -name 'ai_inspector_engine.so' -path '*/epan/*' | head -1)
ui_so=$(find "$build_dir/run" -name 'ai_inspector.so' -path '*/ui/*' | head -1)
[ -n "$engine_so" ] && [ -n "$ui_so" ] || { echo "Built plugins not found under $build_dir/run" >&2; exit 1; }
version_dir=$(basename "$(dirname "$(dirname "$engine_so")")")   # e.g. 4-7

if [ "$install_mode" = personal ]; then
  dest="$HOME/.local/lib/wireshark/plugins/$version_dir"
  say "Installing to $dest"
  mkdir -p "$dest/epan" "$dest/ui"
  cp -f "$engine_so" "$dest/epan/"
  cp -f "$ui_so" "$dest/ui/"
  # Avoid "found in multiple directories" when the dev build scans both folders.
  rm -f "$engine_so" "$ui_so"
  engine_so="$dest/epan/ai_inspector_engine.so"
  ui_so="$dest/ui/ai_inspector.so"
fi

if [ "$run_tests" = 1 ]; then
  say "Unit tests (engine helpers, AI client, redaction, settings, panel)"
  cmake -S "$ai_inspector_root" -B "$build_dir/ai-inspector-tests" -G Ninja -DCMAKE_PREFIX_PATH="$prefix_path" >/dev/null
  cmake --build "$build_dir/ai-inspector-tests" -j "$jobs"
  ctest --test-dir "$build_dir/ai-inspector-tests" --output-on-failure

  say "Integration tests (TShark engine$( [ "$gui_test" = 1 ] && echo ' + in-app UI self-test'))"
  venv="$build_dir/ai-inspector-venv"
  if [ ! -x "$venv/bin/python3" ]; then
    python3 -m venv "$venv"
    "$venv/bin/python3" -m pip install --quiet --upgrade pip
    "$venv/bin/python3" -m pip install --quiet scapy cryptography
  fi
  gui_flag=""
  [ "$gui_test" = 1 ] && gui_flag="--gui"
  "$venv/bin/python3" "$ai_inspector_root/tests/run_tests.py" --build-dir "$build_dir" $gui_flag
fi

ws_exe="$build_dir/run/wireshark"
[ -x "$build_dir/run/wireshark.app/Contents/MacOS/wireshark" ] && ws_exe="$build_dir/run/wireshark.app/Contents/MacOS/wireshark"
say "Done"
cat <<EOF
Engine plugin : $engine_so
UI plugin     : $ui_so
Run Wireshark : sh $ai_inspector_root/tools/run-wireshark.sh
TShark report : $build_dir/run/tshark -r capture.pcapng -q -z ai_inspector,report

In Wireshark: Tools > AI Inspector > Open Inspector Panel, then the gear button to add an AI key.
EOF
